adding core,logger, utilities layers to Test Automation Framework
KrisAramis/Test_Automation_Framework_Selenium pull request #1
Opened 2023-08-21 20:49 UTC by KrisAramis

Please review my Homework for Test Automation Framework

2023-09-05 18:49 UTC, MariaEroshevich requested changes

2023-09-05 18:49 UTC, MariaEroshevich commented on WebApplicationTests/WebApplicationCore/BasePage/BasePage.cs
> +        //public WebElement AcceptAllCookiesButton = new WebElement()
remove commented part of the code

2023-09-05 18:49 UTC, MariaEroshevich commented on WebApplicationTests/WebApplicationWeb/Helper/TestSettings.cs
> +namespace WebApplicationWeb.Helper
You have this class in Core part. Why did you add the duplicate to Web part?

2023-09-05 18:49 UTC, MariaEroshevich commented on WebApplicationTests/WebApplicationWeb/PageObjects/SearchResultsPage.cs
> +    private IWebDriver _driver;
You should use BrowserFactory class to use FindElements method instead of creating new instance of IWebDriver.

2023-09-05 18:49 UTC, MariaEroshevich commented on WebApplicationTests/RunSettings.xml
> +﻿<?xml version="1.0" encoding="utf-8" ?>
Add screenshot maker implementation.

2023-09-30 09:28 UTC, KrisAramis commented on WebApplicationTests/RunSettings.xml
> +﻿<?xml version="1.0" encoding="utf-8" ?>
added

2023-09-30 09:29 UTC, KrisAramis commented on WebApplicationTests/WebApplicationCore/BasePage/BasePage.cs
> +        //public WebElement AcceptAllCookiesButton = new WebElement()
removed

2023-09-30 09:30 UTC, merged